<a href="https://colab.research.google.com/github/pukung375/CE888/blob/master/Lab1/Lab__1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


1.Create a (4 x 2) integer array and print it's attributes

In [3]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]



2.Create an array of dimension (1,10) and sort it in ascending and descending order

In [4]:
array = np.arange(10)
array_ascending = np.sort(array)
print(array_ascending )
array_descending = array_ascending[::-1]
print(array_descending)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


3.Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [5]:
a = np.arange(1,10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]



4.Stack two arrays of any size horizontally and vertically

In [6]:

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
array1 = np.concatenate((a, b), axis=0)
array2 = np.concatenate((a, b.T), axis=1)
print("vertically")
print(array1)
print("-----------------")
print("horizontally")
print(array2)

vertically
[[1 2]
 [3 4]
 [5 6]]
-----------------
horizontally
[[1 2 5]
 [3 4 6]]



5.Create two array of same size and find commom elements

In [7]:
a = np.arange(1,5).reshape(2,2)
b = np.array([[1,3],[4,5]])
print("---- Array a ----")
print(a)
print("---- Array b ----")
print(b)
print("---- Comment Elements----")
np.intersect1d(a,b)

---- Array a ----
[[1 2]
 [3 4]]
---- Array b ----
[[1 3]
 [4 5]]
---- Comment Elements----


array([1, 3, 4])

6.Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [8]:
a = np.random.randint(1,100,25).reshape(5,5)
print(a)
maxValue_c = np.amax(a, axis=0)
print("--- Maximum value from each column ---")
print(maxValue_c)
minValue_c = np.amin(a, axis=0)
print("--- Minimum value from each column ---")
print(minValue_c)

maxValue_r = np.amax(a, axis=1)
print("--- Maximum value from each row ---")
print(maxValue_r)
minValue_r = np.amin(a, axis= 1)
print("--- Minimum value from each row ---")
print(minValue_r)

[[70 20 90 66 54]
 [86 56 52 90 64]
 [55 85 70 23 13]
 [21 38 58 69 28]
 [48 43 10 21 28]]
--- Maximum value from each column ---
[86 85 90 90 64]
--- Minimum value from each column ---
[21 20 10 21 13]
--- Maximum value from each row ---
[90 90 85 69 48]
--- Minimum value from each row ---
[20 52 13 21 10]


7.Create an array of size 100 and compute the mean, median, standard deviation.

In [9]:
a = np.random.randint(1,100,100).reshape(10,10)
print(a)
print("--- Mean Value ---")
MeanValue = np.mean(a)
print(MeanValue)
print("--- Median Value ---")
MedianValue = np.median(a)
print(MedianValue)
print("--- standard deviation ---")
stdValue = np.std(a)
print(stdValue)

[[58  6 50 73 76 68 72 24 49 29]
 [47 71  5  9 61 22 79 50 86 89]
 [ 5 71 77 37 80 38 37 97 26 22]
 [80 71 23 31 50 67 72 36  9 10]
 [21 64 80 80 38 10 82 48 41 71]
 [87 12 71 57 94 22 68 28 74 64]
 [74 10 94 70  6 98 86 40 69 79]
 [61 84 58 98 43  9 90 82 32 60]
 [36 23 41 68 42 99 87 32 90 74]
 [41  1 51 81 63 93 29 78 85 96]]
--- Mean Value ---
55.28
--- Median Value ---
61.0
--- standard deviation ---
27.76475463604892



8.Normalize a 5x5 random matrix

In [10]:
a = np.random.randint(1,20,25).reshape(5,5)
print(a)

[[13 18  9 16  8]
 [ 8  3 19  1  6]
 [13 17 12 17 13]
 [19  7 12 16 14]
 [ 1  2  4 15 15]]



9.Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

In [11]:
a = np.arange(1,49).reshape(4,4,3)
b = np.arange(1,17).reshape(4,4)

a*b[:,:,None]

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27],
        [ 40,  44,  48]],

       [[ 65,  70,  75],
        [ 96, 102, 108],
        [133, 140, 147],
        [176, 184, 192]],

       [[225, 234, 243],
        [280, 290, 300],
        [341, 352, 363],
        [408, 420, 432]],

       [[481, 494, 507],
        [560, 574, 588],
        [645, 660, 675],
        [736, 752, 768]]])