<a href="https://colab.research.google.com/github/pukung375/CE888/blob/master/Lab5/Recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

#Load the data from ``jester-data-1.csv''

In [0]:
df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab5-recommender/jester-data-1.csv', header=None)
df

0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]

In [0]:
arr = df.copy() 
arr = arr.drop(arr.columns[0], axis=1)

In [0]:
arr = df.values
print(arr.shape)

(24983, 101)


In [0]:
rated = np.where(arr!=99)
rated

(array([    0,     0,     0, ..., 24982, 24982, 24982]),
 array([ 0,  1,  2, ..., 70, 71, 87]))

In [0]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

1835357 (1835357,)


In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [0]:
new_arr, idx = replace(arr, 0.1)

In [0]:
arr[idx[0][0], idx[1][0]]

1.75

In [0]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [0]:
n_latent_factors = 2

user_ratings = df.values
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=1000, alpha=0.0001):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if (rating!=99):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 1) == 0:
            print(mse)

In [0]:
# caseA1: latent_factors=2, iterations=20, alpha=0.0001
sgd(iterations=20, alpha=0.0001)  # Note how the MSE decreases with the number of iterations

57.96549805499956
31.390232103846078
25.263775983887083
24.70128895288731
24.65517984415492
24.65001283801267
24.64866310238358
24.647781064152632
24.646963792889075
24.646104028562142
24.645105895328392
24.643832281615705
24.642069725016576
24.639477439986763
24.635504759856047
24.629257233751474
24.61928078861563
24.603217124525663
24.577262582550052
24.535342829291597


In [0]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[ 7.501e+01,  6.349e-01,  8.426e-02, ...,  6.020e-01, -2.028e-01,
         9.650e-01],
       [ 9.636e+01,  1.096e+00,  3.584e-01, ...,  9.731e-01,  5.516e-02,
         1.460e+00],
       [ 5.464e+01,  4.888e-01,  8.478e-02, ...,  4.573e-01, -1.182e-01,
         7.237e-01],
       ...,
       [ 3.812e+01,  4.088e-01,  1.196e-01, ...,  3.672e-01, -6.166e-03,
         5.582e-01],
       [ 3.757e+01,  3.761e-01,  9.394e-02, ...,  3.429e-01, -3.630e-02,
         5.291e-01],
       [ 7.449e+01,  9.700e-01,  3.864e-01, ...,  8.396e-01,  1.807e-01,
         1.226e+00]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [0]:
comparison_data
# For each data point, the number on the left is the original value from the dataset, the number on the right is the prediction

0    ...                         100
0        (74.0, 75.00612934856188)  ...  (99.0, 0.9650437293018728)
1        (100.0, 96.3570077960247)  ...  (1.07, 1.4604597728613058)
2       (49.0, 54.644552646742895)  ...  (99.0, 0.7237132238686548)
3        (48.0, 49.74792648686631)  ...  (99.0, 0.9714483359639794)
4        (91.0, 93.95468641819883)  ...   (1.6, 1.3342607289951585)
...                            ...  ...                         ...
24978  (100.0, 103.13765198118071)  ...  (7.43, 1.5667488595096954)
24979    (91.0, 85.49752427869464)  ...  (8.45, 1.1589792269677095)
24980   (39.0, 38.118480217605224)  ...  (99.0, 0.5581883404071483)
24981    (37.0, 37.57188237752632)  ...  (99.0, 0.5290556809242652)
24982    (72.0, 74.48764530749462)  ...   (99.0, 1.225526633557988)

[24983 rows x 101 columns]

In [0]:
# Calculate the performance (e.g., MSE) of the algorithm on the validation dataset
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseA1=sum(error)/len(error)
print("caseA1: ",mseA1)

caseA1:  24.506369752671773


Repeat the two points above changing hyper-parameters (i.e., learning rate, number of iterations of SVD, number of latent factors, etc.) as needed to get good results (you can create multiple validation sets if you want, and run a bootstrap!)

In [0]:
# caseA2: latent_factors=2, iterations=30, alpha=0.0001
n_latent_factors = 2
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=15,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseA2=sum(error)/len(error)
print("caseA2: ",mseA2)

60.1321917780049
32.058313661646125
25.47985278182832
24.71338417720438
24.631563268206186
24.611355580330244
24.59776692956536
24.58546861405063
24.573802629304325
24.56261370350433
24.5518008269262
24.541248133244608
24.530798350228725
24.520224885536322
24.50919129658779
caseA2:  40.38410888844587


In [0]:
# caseA2: latent_factors=2, iterations=30, alpha=0.0001
n_latent_factors = 2
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=30,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseA2=sum(error)/len(error)
print("caseA2: ",mseA2)

60.1321917780049
32.058313661646125
25.47985278182832
24.71338417720438
24.631563268206186
24.611355580330244
24.59776692956536
24.58546861405063
24.573802629304325
24.56261370350433
24.5518008269262
24.541248133244608
24.530798350228725
24.520224885536322
24.50919129658779
24.497189499577072
24.48344519343043
24.4667737141032
24.445362308386137
24.41644626618284
24.375839218132253
24.317280430108124
24.231594450592077
24.10576394079595
23.92226859066293
23.659520377216243
23.29486659069954
22.81186301064788
22.21188170738513
21.5252452352359
caseA2:  45.78733594543292


In [0]:
# caseA3: latent_factors=2, iterations=40, alpha=0.0001
n_latent_factors = 2
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=40,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseA3=sum(error)/len(error)
print("caseA3: ",mseA3)

60.1321917780049
32.058313661646125
25.47985278182832
24.71338417720438
24.631563268206186
24.611355580330244
24.59776692956536
24.58546861405063
24.573802629304325
24.56261370350433
24.5518008269262
24.541248133244608
24.530798350228725
24.520224885536322
24.50919129658779
24.497189499577072
24.48344519343043
24.4667737141032
24.445362308386137
24.41644626618284
24.375839218132253
24.317280430108124
24.231594450592077
24.10576394079595
23.92226859066293
23.659520377216243
23.29486659069954
22.81186301064788
22.21188170738513
21.5252452352359
20.81163082651254
20.14246075417658
19.573449824491508
19.1272900081051
18.796702882633884
18.55922303553109
18.390347789005954
18.26983911263935
18.182918919817677
18.11935662736073
caseA3:  43.28096558593547


In [0]:
# caseB1: latent_factors=3, iterations=20, alpha=0.0001
n_latent_factors = 3
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=40,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseB1=sum(error)/len(error)
print("caseB1: ",mseB1)

52.92388325845578
31.126941478712233
26.02575979848225
24.886093042101407
24.65621102983484
24.600517385075356
24.57793106430558
24.560914301704386
24.54312976924008
24.521910390078272
24.494654271619744
24.457748235711257
24.405841099619256
24.331027260362102
24.221897345159086
24.062659556814975
23.832933741448933
23.509445216093198
23.0714065246515
22.51076361914311
21.844910255210284
21.12324419142956
20.41698303193601
19.792942582789156
19.28899497287619
18.908682498835145
18.633338795367933
18.437534486998846
18.298437682894303
18.198739745406424
18.126277106683258
18.07274276490634
18.03248923447047
18.001651131298367
17.97755182838916
17.958311891089522
17.942591118217173
17.92941743312524
17.918072277852023
17.90801303042142
caseB1:  35.12305448970637


In [0]:
# caseB2: latent_factors=4, iterations=30, alpha=0.0001
n_latent_factors = 4
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=40,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseB2=sum(error)/len(error)
print("caseB2: ",mseB2)

48.83429863619704
30.831657764786517
26.540468639631072
25.16204167424905
24.754502541891153
24.630085228829678
24.586605351394503
24.566260206216217
24.552301034677143
24.539473187510218
24.52560331334798
24.509104217185776
24.488087775881453
24.459851811287535
24.420362534613492
24.3635967125414
24.28070362503694
24.1590615541253
23.98154342593841
23.7267647703872
23.371734876056877
22.30635115637876
21.62185404889653
20.902592782435843
20.220409273142316
19.634076456949757
19.170050067784164
18.823616348617456
18.573217305132367
18.394182677160618
18.26570680282146
18.172416404044952
18.10358308601706
18.051857474526656
18.01220168496164
17.981129769225827
17.95619760563608
17.935665338397918
17.918273483498776
caseB2:  34.02795290249243


In [0]:
# caseB3: latent_factors=5, iterations=40, alpha=0.0001
n_latent_factors = 5
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=40,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseB3=sum(error)/len(error)
print("caseB3: ",mseB3)

45.701115620230716
30.60445861964782
26.94855095195479
25.472973867642946
24.911886150018265
24.698450302401636
24.61349092274839
24.575441273637452
24.554114073597237
24.538019885244896
24.522272346647494
24.50406467867437
24.480847472228742
24.44940481641394
24.405148120721055
24.34136332369689
24.248337691753534
24.112470217371907
23.91576884593499
23.636641436265396
23.253478545132378
22.752515558298708
22.13936794353551
21.448580969132667
20.741203613508777
20.085486640883484
19.53117539395372
19.095983150948097
18.770813455598784
18.533935440015608
18.362481359931845
18.237642117475666
18.14553558163693
18.076368329186945
18.02332103230335
17.9816331568905
17.94794860862841
17.919869016993683
17.89565210743648
17.874007598923033
caseB3:  31.958280203107382
